In [9]:
import torch, torchvision
import numpy as np
verbose = True

In [10]:
# Helper function to print resulting matrices if vebrose is equal to true
def verb(p):
    if verbose:
        print(p)

# 1. Multiple views of a storage
Generate the matrix with no python loop. 

1 2 1 1 1 1 2 1 1 1 1 2 1  
2 2 2 2 2 2 2 2 2 2 2 2 2  
1 2 1 1 1 1 2 1 1 1 1 2 1  
1 2 1 3 3 1 2 1 3 3 1 2 1  
1 2 1 3 3 1 2 1 3 3 1 2 1  
1 2 1 1 1 1 2 1 1 1 1 2 1  
2 2 2 2 2 2 2 2 2 2 2 2 2  
1 2 1 1 1 1 2 1 1 1 1 2 1  
1 2 1 3 3 1 2 1 3 3 1 2 1  
1 2 1 3 3 1 2 1 3 3 1 2 1  
1 2 1 1 1 1 2 1 1 1 1 2 1  
2 2 2 2 2 2 2 2 2 2 2 2 2  
1 2 1 1 1 1 2 1 1 1 1 2 1  

Hint: Use torch.full, and the slicing operator. 


In [11]:
# Create 13x13 matrix filled with 1's
t = torch.full((13, 13), 1 )
# Make colomns of 2's
t[:,1].fill_(2)
t[:,6].fill_(2)
t[:,11].fill_(2)
# Make rows of 2's
t[1,:].fill_(2)
t[6,:].fill_(2)
t[11,:].fill_(2)
# Make squars of 3's 
t[3:5,3:5].fill_(3)
t[3:5,8:10].fill_(3)
t[8:10,3:5].fill_(3)
t[8:10,8:10].fill_(3)

verb(t)
# --------------------
#! Method B a simpler method
# --------------------




tensor([[1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1]])


# 2 Eigendecomposition
Without using python loops, create a square matrix M (a 2d tensor) of dimension 20 x 20, filled with
random Gaussian coeffcients, and compute the eigenvalues of:
$
M^{-1} \underbrace{\left [\begin{array}{ccccc}
1 & 0 & \ldots & \ldots & 0 \\
0 & 2 & & & \vdots \\
\vdots & & \ddots & & \vdots \\
\vdots & & & 19 & 0 \\
0 & \ldots & \ldots & 0 & 20
\end{array} \right]}_{\operatorname{diag}(1, \ldots, 20)} M
$

Hint: Use torch.empty, torch.normal_, torch.arange, torch.diag, torch.mm, torch.inverse,
and torch.eig.

In [12]:
# Create a diagonal matrix 20x20 
d = torch.arange(20).add_(1)  # makes a 1D matrix [1 2 ... 20]
verb(d)
D = torch.diag(d) # makes a diagonal using d as diagonal 
verb(D)


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])
tensor([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0],
        [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0],
        [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0],
        [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0],
        [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0],
        [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0],
        [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0],
        [ 0,

In [13]:
# Create a random matrix M and M_inv
M = torch.empty(20,20).normal_(mean=4,std=0.5)

M_inv = torch.inverse(M)
verb(M)

tensor([[3.8663, 4.2686, 3.7813, 3.6810, 3.5208, 4.1466, 4.4762, 3.3589, 3.9556,
         3.3158, 4.0111, 3.6273, 3.9746, 4.2740, 4.2680, 4.5459, 3.6083, 3.8681,
         3.5847, 4.2777],
        [4.0136, 4.6308, 4.3074, 3.4292, 3.5957, 4.1231, 4.3064, 3.7701, 4.5104,
         5.4170, 3.9510, 3.1711, 3.5750, 4.8573, 3.7730, 3.0823, 4.0223, 3.8744,
         4.9383, 2.9181],
        [3.6269, 4.6741, 4.0513, 3.8109, 4.8432, 3.3862, 3.8071, 4.2361, 4.3120,
         2.9131, 4.7547, 4.3344, 4.0797, 3.6660, 4.3159, 2.6780, 3.8392, 3.5844,
         3.6379, 4.4927],
        [3.0706, 4.1264, 3.7699, 4.0114, 3.7870, 4.4327, 4.1918, 4.1835, 4.5166,
         3.1702, 4.1007, 3.9547, 4.5832, 4.3269, 4.0773, 4.2801, 3.7432, 4.2624,
         4.3062, 4.8547],
        [4.4186, 4.4835, 4.1155, 4.4371, 3.4391, 3.8183, 3.6013, 4.1968, 3.8455,
         3.6515, 4.5546, 3.6884, 4.2446, 4.2197, 3.4299, 3.6798, 3.9451, 3.2644,
         3.5209, 3.0243],
        [5.2812, 3.0952, 3.9852, 4.2826, 5.2423, 4.4746, 4.2

In [14]:
# Matrix multiplication
#! couldn't use torch.mm because of different data types
mul = M*D*M_inv
verb(mul)

tensor([[ 11.2402,   0.0000,  -0.0000,  -0.0000,  -0.0000,   0.0000,  -0.0000,
          -0.0000,  -0.0000,  -0.0000,   0.0000,   0.0000,  -0.0000,  -0.0000,
           0.0000,  -0.0000,  -0.0000,   0.0000,   0.0000,   0.0000],
        [ -0.0000,  -0.0759,   0.0000,   0.0000,   0.0000,  -0.0000,  -0.0000,
          -0.0000,   0.0000,   0.0000,  -0.0000,  -0.0000,   0.0000,  -0.0000,
          -0.0000,   0.0000,   0.0000,  -0.0000,  -0.0000,  -0.0000],
        [ -0.0000,  -0.0000,   5.0626,   0.0000,   0.0000,  -0.0000,   0.0000,
           0.0000,  -0.0000,   0.0000,  -0.0000,   0.0000,   0.0000,   0.0000,
          -0.0000,  -0.0000,   0.0000,   0.0000,  -0.0000,  -0.0000],
        [ -0.0000,  -0.0000,  -0.0000,  16.0997,   0.0000,  -0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,  -0.0000,   0.0000,   0.0000,
          -0.0000,  -0.0000,   0.0000,  -0.0000,  -0.0000,  -0.0000],
        [ -0.0000,  -0.0000,   0.0000,   0.0000,   0.5029,  -0.0000,  -0.0000,
         

In [15]:
# Eigen Values
eig = torch.inverse(mul)
verb(eig)

tensor([[  0.0890,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,  -0.0000],
        [  0.0000, -13.1728,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,  -0.0000],
        [  0.0000,   0.0000,   0.1975,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,  -0.0000],
        [  0.0000,   0.0000,   0.0000,   0.0621,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,  -0.0000],
        [  0.0000,   0.0000,   0.0000,   0.0000,   1.9885,   0.0000,   0.0000,
         

# 3 Flops per second
Generate two square matrices of dimension 5000 x 5000 filled with random Gaussian coefficients,
compute their product, measure the time it takes, and estimate how many 
floating point products
have been executed per second (should be in the billions or tens of billions).
Hint: Use torch.empty, torch.normal_, torch.mm, and time.perf_counter.

In [16]:
# Python program to show time by perf_counter()  
from time import perf_counter 

# Generate two square matrices of 5000x5000
m1 = torch.empty(5000,5000).normal_(mean=4,std=0.5)
m2 = torch.empty(5000,5000).normal_(mean=4,std=0.5)

# Start the stopwatch / counter 
t1_start = perf_counter()  

# compute their product
product = m1*m2

# Stop the stopwatch / counter 
t1_stop = perf_counter() 
t_duration = t1_stop-t1_start
  
print("Elapsed time during the whole program in seconds:", t_duration ) 

# Estimate the number of floating point products have beend executed per second
prod_per_sec = (5000^3 ) / (t_duration ) #! the number of floating point operations in nxn time n#n is equal to n^3
print("Estimate the number of floating point products have beend executed per second", prod_per_sec)


Elapsed time during the whole program in seconds: 0.04457999999999984
Estimate the number of floating point products have beend executed per second 112225.21310004526


# 4 Playing with strides
Write a function mul_row, using python loops (and not even slicing operators), that gets a 2d tensor
as argument, and returns a tensor of same size, whose first row is identical to the first row of the
argument tensor, the second row is multiplied by two, the third by three, etc.

For instance:
>>> m = torch.full((4, 8), 2.0)
>>> m
tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
[2., 2., 2., 2., 2., 2., 2., 2.],
[2., 2., 2., 2., 2., 2., 2., 2.],
[2., 2., 2., 2., 2., 2., 2., 2.]])
>>> mul_row(m)

tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
[4., 4., 4., 4., 4., 4., 4., 4.],
[6., 6., 6., 6., 6., 6., 6., 6.],
[8., 8., 8., 8., 8., 8., 8., 8.]])


Then, write a second version named mul_row_fast, using tensor operations.
Apply both versions to a matrix of size 1000 x 400 and measure the time each takes (there should
be more than two orders of magnitude difference).

Hint: Use broadcasting and torch.arange, torch.view, torch.mul, and time.perf_counter.

In [17]:
# Method with loop
def mul_row(arg_tensor):
    t2_start = perf_counter()  
    
    m = torch.empty(arg_tensor.size())
    rows = arg_tensor.size(0)
    for r in range(rows):
        m[r,:] = torch.mul(arg_tensor[r,:],(r+1))
    
    t2_stop = perf_counter()  
    print("Elapsed time during mul_row in seconds:", (t2_stop-t2_start) ) 

    return m
        

In [18]:
# Method using tensor operations"
def mul_row_fast(arg_tensor):
    t3_start = perf_counter()  
    
    rows = arg_tensor.size(0)
    c = torch.arange(rows).add_(1) 
    mt = torch.transpose(arg_tensor,0,1)
    mul = torch.transpose(mt*c,0,1)
    
    t3_stop = perf_counter() 
    print("Elapsed time during mul_row_fast in seconds:", (t3_stop-t3_start) ) 
    
    return  mul


In [19]:
m = torch.full((1000, 400), 1.0)

# m = torch.full((4, 8), 2.0)
m1 = mul_row(m)
m2 = mul_row_fast(m)

#! there should be more than two orders of magnitude difference

    
    

Elapsed time during mul_row in seconds: 0.03776879999999849
Elapsed time during mul_row_fast in seconds: 0.0006641999999992265
